trigger:
  branches:
    include:
      - '*'
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    dotnet build --configuration Release
  displayName: 'Build'

- bash: |
    export Version=${TagName:1}
    dotnet pack -c Release
    dotnet nuget push nupkg/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
  env:
    TagName: '$(Build.SourceBranchName)'
    NUGET_KEY: '$(NUGET_KEY)'
  displayName: 'Release'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
